### PR TITLE
Use Prettier to format code

### PR DESCRIPTION
**Pull request by captbaritone**
This might cause some merge conflicts, but resolving them should be as easy as taking the other pull request's code an re-running `npm run link -- --fix`.

### CODE REVIEW

**Comment by captbaritone** [comment]
Rebased.

**Comment by msrose** [comment]
I really like this, particularly for deciding when and how to line break, but I'd like to use the [singleQuotes setting](https://github.com/prettier/prettier#quotes).

Also, how does running `npm run link -- --fix` end up running prettier? That's a bit of a mystery to me :P

**Comment by captbaritone** [comment]
I'll update the setting. The `--fix` support is added by the ESLint-plugin-Prettier plugin, which just runs the file through Prettier and complains if it doesn't match. If asked to "fix" it just reformists the entire file.

**Comment by captbaritone** [comment]
Updated.

**Comment by captbaritone** [comment]
In the future, it might be nice to pull the config out into it's own file or package.json (I think it supports that) so that editors and other tools can discover it.

**Comment by msrose** [comment]
Ohhh it's just invoking eslint then - I was confused at first since the PR says npm run **link** --fix, but guessing that's an autocorrect of "lint" or something 👍 Unfortunate since `npm link` is actually a thing. Thanks, makes sense!

**Pull request merged**
